### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by i-saint** [legeclodb/legeclodb#1]
- [ ] 組み合わせ検索ロジックを C++ (wasm) で再実装
~~Vue3 移行~~ bootstrap の Vue3 対応が極めてダメなので今プロジェクトはこのままで…
- [x] 割合バフ・デバフは何らかの形で効果量も考慮したい→組み合わせ検索
- [x] ステータス値の表示とソート
  - [x] レベル・☆などの指定 
- [x] 戦闘力の算出方法調査
- [x] ランダムバフ・デバフ内訳調査
- [x] pagination
- [x] 召喚ユニット対応
- [x] タレント/サポートアクティブのレベル対応
- [x] スキル検索 (とりあえずフリーワード検索で実現)
- [x] フリーワード検索
- [x] タグの該当数表示
- [x] スキルの射程・範囲・コスト表示
- [x] 装備の項目
- [x] サポートキャラの項目
- [x] メインキャラの項目
